name: Actions Workflow

on: [ push ]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list
        run: |
          pwd
          ls
      - name: Sime JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: SAURAV
      - name: Log greeting time
        run: echo "${{steps.greet.outputs.time}}"